### ISSUE TITLE
`fatal error: sync: unlock of unlocked mutex` when adding a directory with many files

### ISSUE THREAD

**Issue by postables** [sahib/brig#35]
**Describe the bug**
When adding a directory with many files (in this case 3922) an error is given that says `fatal error: sync: unlock of unlocked mutex` causing the brig daemon to crash.

I've uploaded the directory that was giving me issues to ipfs with hash [QmbLsNtkEoprt25nYD2GNHPjAsgQRCJQARMnmTsSFLocSe](https://gateway.temporal.cloud/ipfs/QmbLsNtkEoprt25nYD2GNHPjAsgQRCJQARMnmTsSFLocSe) <- is a link to a gateway

I've also uploaded the log from brig that is produced when the crash occurs to ipfs with hash [QmTQh7BGBd8K2eYAAVTPRhduxBgiUHXY1NyjJN1JHfTCS9](https://ipfs.io/ipfs/QmTQh7BGBd8K2eYAAVTPRhduxBgiUHXY1NyjJN1JHfTCS9) <- another gateway link

**To Reproduce**

1. Download the directory from [here](https://gateway.temporal.cloud/ipfs/QmbLsNtkEoprt25nYD2GNHPjAsgQRCJQARMnmTsSFLocSe)
2. Add with `brig stage add <directory>`

**Please always include the output of the following commands in your report!**

* ``brig bug -s``
```
go version:     go version go1.12 linux/amd64
uname -s -v -m: Linux #17pop0~18.04.1-Ubuntu SMP Fri Mar 8 17:51:15 UTC 2019 x86_64
brig client version: v0.4.0+b3de1f1 [build: 2019-03-19T15:36:05+0000]
brig server version: v0.4.0+b3de1f1+b3de1f119735e0f3fb5e5f9bccc7893418c098d4
ipfs version:        0.4.19+
```
**Expected behavior**
Be able to successfully add the file to brig without crashing or error

**Additional context**

* brig is running with a password
* ipfs daemon is using `badgerds` as the datastore

My IPFS datastore config
```json
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "child": {
        "path": "badgerds",
        "syncWrites": true,
        "truncate": true,
        "type": "badgerds"
      },
      "prefix": "badger.datastore",
      "type": "measure"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },

```

**Comment by sahib** [comment]
Hello @postables,

thanks for the detailed report. I managed to write a test case that reproduces the error. It's an edge case in the way we use the badger API that probably was not expected by the authors (mixing read-only and read-write transactions). It's actually a wonder this never happened to me. The fixed might take a bit though.

P.S: Actually an good idea to include the IPFS config in the bug report. I should make ``brig bug`` include this info, although it's not important for this particular issue.

**Comment by postables** [comment]
No problem! Yes that could be a particularly useful feature to have with `brig bug`! If the issue is just in the way brig interfaces with the badger API, i'll switch over to using an IPFS node with flatfs/leveldb instead.

Thanks for the quick response!

**Comment by sahib** [comment]
> [...] i'll switch over to using an IPFS node with flatfs/leveldb instead.

That has nothing to do with it. This is about the badger database of ``brig``.

**Comment by sahib** [comment]
Also, I should have fixed as of 27044373. If you want, you can try to see if it fixes your issue.

**Comment by postables** [comment]
Ah okay that makes sense. Perfect, i'll try the fix out tonight :fireworks:

**Comment by postables** [comment]
Had a chance to test this out, I'm on git commit `eabcaef7245fd48e156312277bd5ff067570817e` and have the error still

**Comment by sahib** [comment]
You have to check out the develop branch. You used the master branch.Am 24.03.2019 10:16 vorm. schrieb postables <notifications@github.com>:Had a chance to test this out, I'm on git commit eabcaef7245fd48e156312277bd5ff067570817e and have the error still

**Comment by postables** [comment]
:man_facepalming: Just tried with the develop branch and so far so good! :D

**Comment by sahib** [comment]
Alright. :+1: 

Please re-open if the problem persists.
